### ISSUE TITLE
Error while running the code 

### ISSUE THREAD

**Issue by rns0869** [shayantaherian/Object_Detection_Carla#4]
![IMG_20230301_110254](https://user-images.githubusercontent.com/79132373/222107294-eefce794-5838-425f-92cb-738b82a76a5a.jpg)
I face this error while running the object detection.py file. Can you help me out?

**Comment by shayantaherian** [comment]
have you checked if your list size is correct ? I suggest you put bullet point on each line and debug. It seems that there are lists in your script that either hasn't been inisiatilized yet or there is a mismatch somewhere
