### ISSUE TITLE
Yolo Code

### ISSUE THREAD

**Issue by shehrozbashir546** [shayantaherian/Object_Detection_Carla#5]
Hi I am trying to understand how you implemented the yolo code from line 765-782. In my use case, I am also using opencv.dnn to read the weights, generate the blob and forward it. 

Can you explain your reasoning behind it or point me to the resource where you learnt it from?

**Comment by shayantaherian** [comment]
sorry to respond so late. Well the blob and .dnn is objects that we need to use them for detection. simply after blob we are extracting bounding boxes based on each class and then. use NMS to remove the duplicate. There are many tutorials onlin such as https://pyimagesearch.com/2018/11/12/yolo-object-detection-with-opencv/.
