### ISSUE TITLE
Missing utils.py File in Repository

### ISSUE THREAD

**Issue by i-kj** [shayantaherian/Object_Detection_Carla#6]
Hello,

I was trying to run the Object_Detection.py script from your repository, but it seems that the utils.py file is missing. The script imports this file, and without it, the code doesn't run.

Could you please add the missing utils.py file to the repository or provide guidance on how to proceed without it?

In addition to that I am also seeing the below problems:
![Object detection issue](https://github.com/shayantaherian/Object_Detection_Carla/assets/141944156/d922f5f3-3cec-4723-9391-0a8afc3502a8)

I followed exactly what is mentioned in READ.me 

Thank you for your time and for sharing this project!

Best regards,
Praveen KJ

**Comment by shayantaherian** [comment]
Hi,
Yes i can see that the utils.py is missing. I believe this file can be found in carla carla simulator package when you download. unfortunately i do not have this file as i have done this project long time ago. In any case i will try to find the missing file in the mean time.
Regards,
Shayan

**Comment by i-kj** [comment]
Thank you. Suggestion helped me by pass the issue.
