### ISSUE TITLE
yolo detection

### ISSUE THREAD

**Issue by minyunh** [shayantaherian/Object_Detection_Carla#8]
Hi, 
How can it only detect about car, person, traffic light?
Because it detect everything as a sofa.

![2024-03-07 16-10-05 的螢幕擷圖](https://github.com/shayantaherian/Object_Detection_Carla/assets/66958434/948cfd91-1faf-41f2-87ca-3a8dbc8413b0)

**Comment by shayantaherian** [comment]
Hi, i had this problem when i used yolov3. if you change the weight file and its corresponding config to yolov4, i believe it will solve the issue. simply just download the weights file online.

**Comment by minyunh** [comment]
Thanks a lot. It is glad to receive a reply from you!
Now executed successfully!
